### ISSUE TITLE
Release on pecl

### ISSUE THREAD

**Issue by Seldaek** [FriendsOfPHP/uprofiler#11]
Would it be possible to push releases to pecl so that the windows builders create DLLs automatically over there?

**Comment by mstyles** [comment]
+1 for pecl, it would make me very happy

**Comment by fabpot** [comment]
@pierrejoye Can you see how we can get uprofiler on pecl?

**Comment by fabpot** [comment]
Closing as it's going to happen apparently and I won't fight for that. Sorry.
