### ISSUE TITLE
Structure of the src

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/uprofiler#24]
Hi,

What is the reason to change the structure of the extension? 

config.\* must be on top dir. It is a requirement for pickle or other installer.

We could add support for custom location but it means changing many other areas, including php build scripts themself.

**Comment by jpauli** [comment]
Mmmm no, no reason, that's legacy from the xhprof fork

**Comment by pierrejoye** [comment]
would it possible to change it?

Easy to make pickle supports it, but for windows build with php-src, it is trickier (for one platfrom, other suffers from that too)
