### ISSUE TITLE
Status of project / relationship to phacility/xhprof ?

### ISSUE THREAD

**Issue by avindra** [FriendsOfPHP/uprofiler#25]
Hi,

This project hasnt seen any updates in a while. Also, phacility/xhprof, which is what this is a fork of, has newer commits that are missing form this repo:

https://github.com/phacility/xhprof/commits/master

Is there a plan to keep things in sync? The lack of a proper profiling tool for PHP is apparent, and this XHProf fork looks promising. Keep it going!

**Comment by carlwgeorge** [comment]
The fact that this issue has gone seven months without a response is troubling.

**Comment by jpauli** [comment]
Hello,

We use and develop blackfire now (https://blackfire.io/)
Someone may still fork uprofiler if he wants to.

**Comment by fabpot** [comment]
I think we can close this issue. I've answered some related questions on another thread which summarizes well the status of this project: https://github.com/FriendsOfPHP/uprofiler/issues/28#issuecomment-178694367
