### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by markjeffries** [FriendsOfPHP/uprofiler#28]
Hi,

Do you have any plans to work on the extension for PHP 7?

regards

Mark

**Comment by fabpot** [comment]
There is no plan (at least from me) to add support for PHP7.

PHP7 introduced many internal changes and that means changing almost everything in the uprofiler code. As [Blackfire.io](https://blackfire.io/), which is a project I started a while ago, is going to support PHP7 soon now and as it has a free version that does more than uprofiler, I don't see (personally) the need for uprofiler anymore.

Now, uprofiler is an Open-Source project, so anyone can of course work on PHP7 support.

**Comment by Rarst** [comment]
Unfortunate to hear since uprofiler was pretty much last solution to work on Windows. :(

**Comment by david-garcia-garcia** [comment]
There is no need to port Uprofiler. The Tideways extension takes over. Tideways is an Open Source drop in replacement for XHPROF/UPROFILER that is actively maintained. (Tideways is both the name of the extension and the name of the Cloud service that the maintainers provide for continuous performance integration/monitoring).

https://tideways.io/

They are already supporting Windows in PHP 5.6, you just need to task for the binaries or build them yourself. It looks like they have already ported the extension for PHP7 but have not tried yet:

https://github.com/tideways

I am not related to Tideways in any way, but they have been very helpful with the Windows support and for what they offer this is a hidden gem I was unlucky to to have found earlier.

For the sole reason that this works offline as a drop in replacement for XHPROF/UPROFILER this makes it an awesome tool.

**Comment by Jan-E** [comment]
Without config.w32 you can't just build the extension yourself. There is someone that did a Windows port of the PHP5 extension, but this really needs a lot of changes:
https://github.com/tideways/php-profiler-extension/pull/12

**Comment by david-garcia-garcia** [comment]
I haven't tried to build the extension itself or see how the coding goes, but I signed up for the service, requested windows binaries and they sent them to me (labeled as "experimental" though) to test them out. I've been using this on production for about a couple of weeks now and it works like a charm.

**Comment by Jan-E** [comment]
I've got it to build:
https://github.com/tideways/php-profiler-extension/pull/13

It also compiles for PHP7, but I did not test it yet.

**Comment by beberlei** [comment]
Thanks for the mention of @tideways

We are building the Windows DLLs directly on Appvoyer, so there is where you get the latest ones.

https://ci.appveyor.com/project/beberlei/php-profiler-extension

The Windows support is still beta, there are currnetly two problems:

1. Sometimes the timing results are off, or even jump into negatives. This has been reported by some, but not all users.
2. PHP 7 builds don't work on AppVeyor due to some include errors that need to figure out. PHP 7 is already supported for Linux builds, so this is just a matter of finding the build error for Windows before we have the binaries here.

**Comment by Jan-E** [comment]
PHP7: the link.exe points to VC11.

**Comment by pierrejoye** [comment]
@beberlei how do you build it on appveyor? Create your own makefiles or prj files? 

a config.w32 would be by far easier.

For the timer issue, it is expected given the APIs you use.

**Comment by Jan-E** [comment]
We are way off-topic here, but the branch he is compiling has a config.w32 (with a recent patch to simplify it). But there is something wrong in the appveyor config, because it uses VC11 to compile for PHP7.
https://ci.appveyor.com/project/beberlei/php-profiler-extension/build/job/n8cfi5q05wk8bni7:

	Checking for cl.exe ...  <in default path> 
	  Detected compiler MSVC11 (Visual C++ 2012) 
	  Detected 32-bit compiler 
	Checking for link.exe ...  C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN

**Comment by pierrejoye** [comment]
Right.

Support for their ext can happen there. And they can ask if they need help. :)

**Comment by pierrejoye** [comment]
Oops, reopen

Now about php7 support, I think it would be nice but I lack the time to do it. I also prefer blackfire by far. But a full opensource, even with less features (front and ext), is always good.

**Comment by Jan-E** [comment]
There is a PHP7 port of XHprof: https://github.com/RustJason/xhprof/commits/php7
However, it does not compile on Windows.

**Comment by pierrejoye** [comment]
To work well more than simply compiling is required.

**Comment by fabpot** [comment]
Supporting PHP 7 represents a huge amount of work if we want to do it well. As mentioned by @pierrejoye above, [Blackfire](https://blackfire.io/) is a good free, but not open-source, alternative (full disclosure: I'm also the creator of Blackfire) and Blackfire supports PHP 7 for many different platforms ([announced today](http://blog.blackfire.io/php7-support-blackfire.html)). For all these reasons, I'm closing this issue as a won't fix.

**Comment by beejeebus** [comment]
really disappointed to see this.

this project was a fork, and is now dead end :-(

**Comment by david-garcia-garcia** [comment]
@beejeebus I insist, Tideways is a maintained drop-in replacement for uProfiler. It's Open Source and free to use, and can be used with the Tideways service.
