### ISSUE TITLE
php7   compile error

### ISSUE THREAD

**Issue by kent0106** [FriendsOfPHP/uprofiler#30]
`/home/kent/uprofiler/extension/uprofiler.c:1681: error: ‘zval’ has no member named ‘type’
make: *** [uprofiler.lo] Error 1
`
`/home/kent/uprofiler/extension/uprofiler.c:1670: error: too many arguments to function ‘zend_hash_get_current_key_ex’
/home/kent/uprofiler/extension/uprofiler.c:1673:58: error: macro "zend_hash_get_current_data" passed 2 arguments, but takes just 1
/home/kent/uprofiler/extension/uprofiler.c:1673: error: ‘zend_hash_get_current_data’ undeclared (first use in this function)
`

**Comment by sriharshauppuluri** [comment]
Facing same issue

**Comment by fabpot** [comment]
PHP 7 is not supported. You can use https://blackfire.io instead.
